In [13]:
import numpy as np
import pandas as pd


In [14]:
df = pd.read_excel('onedata.xlsx')
df.head()

buyer  fruits  gender  value
0    ali   apple    male      2
1   noor   mango    male      3
2  wajid  orange  female      4
3  karim  banana    male      4

# apply one hot encoding  using scikit learn

In [22]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(drop='first',dtype=int,sparse_output=False)
df_trf = ohe.fit_transform(df[['buyer','fruits','gender']])

In [23]:
df_trf

array([[0, 0, 0, 0, 0, 0, 1],
       [0, 1, 0, 0, 1, 0, 1],
       [0, 0, 1, 0, 0, 1, 0],
       [1, 0, 0, 1, 0, 0, 1]])

In [24]:
col =ohe.get_feature_names_out()

In [25]:
col

array(['buyer_karim', 'buyer_noor', 'buyer_wajid', 'fruits_banana',
       'fruits_mango', 'fruits_orange', 'gender_male'], dtype=object)

In [26]:
print(df_trf)

[[0 0 0 0 0 0 1]
 [0 1 0 0 1 0 1]
 [0 0 1 0 0 1 0]
 [1 0 0 1 0 0 1]]


In [28]:
pd.DataFrame(data = df_trf,columns=col)

buyer_karim  buyer_noor  buyer_wajid  fruits_banana  fruits_mango  \
0            0           0            0              0             0   
1            0           1            0              0             1   
2            0           0            1              0             0   
3            1           0            0              1             0   

   fruits_orange  gender_male  
0              0            1  
1              0            1  
2              1            0  
3              0            1