In [1]:
import numpy as np
import pandas as pd

In [5]:
df = pd.read_csv("9 covid_toy.csv")
df.head()


age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [6]:
df["city"].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [7]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [9]:
X = df.drop(columns=['has_covid'],axis=1)
y = df['has_covid']

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y , test_size=0.2, random_state=42)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(80, 5) (20, 5) (80,) (20,)


# column transformer 

In [12]:
from sklearn.impute import SimpleImputer
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])
X_test_fever = si.fit_transform(X_test[['fever']])
X_train.shape

(80, 5)

In [13]:
from sklearn.preprocessing import OrdinalEncoder
orn = OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough = orn.fit_transform(X_train[['cough']])
X_test_cough = orn.fit_transform(X_test[['cough']])
print(X_train.shape, X_test.shape)


(80, 5) (20, 5)


In [23]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(drop='first', sparse_output=False)
X_train_gender_city = ohe.fit_transform(X_train[['gender','city']])
X_test_gender_city = ohe.fit_transform(X_test[['gender','city']])
print(X_train.shape, X_test.shape)

(80, 5) (20, 5)


In [24]:
# extracting age 
X_train_age = X_train.drop(columns=["gender","fever","cough","city"]).values
X_test_age = X_test.drop(columns=["gender","fever","cough","city"]).values


In [25]:
print(X_train_age.shape)
print(X_train_fever.shape)
print(X_train_cough.shape)
print(X_train_gender_city.shape)

print(type(X_train_age))
print(type(X_train_fever))
print(type(X_train_cough))
print(type(X_train_gender_city))



(80, 1)
(80, 1)
(80, 1)
(80, 4)
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [27]:
X_train_transformed = np.concatenate((X_train_age,X_train_fever,X_train_gender_city,X_train_cough),axis=1)
X_test_transfromed  = np.concatenate((X_test_age, X_test_fever,X_test_gender_city,X_test_cough),axis=1)

print(X_train_transformed, X_train_transformed.shape)

[[ 81. 101.   0.   0.   0.   1.   0.]
 [  5. 100.   0.   0.   1.   0.   0.]
 [ 19. 100.   0.   0.   1.   0.   0.]
 [ 27. 100.   1.   1.   0.   0.   0.]
 [ 73. 103.   0.   1.   0.   0.   0.]
 [ 70. 103.   1.   0.   1.   0.   1.]
 [ 49. 102.   0.   1.   0.   0.   0.]
 [ 51. 101.   0.   0.   1.   0.   1.]
 [ 64. 101.   0.   1.   0.   0.   0.]
 [ 83. 101.   0.   0.   1.   0.   0.]
 [ 65.  98.   0.   0.   0.   1.   0.]
 [ 18. 104.   0.   0.   0.   0.   0.]
 [ 16. 103.   0.   0.   0.   0.   0.]
 [ 16. 104.   1.   0.   1.   0.   0.]
 [ 27. 100.   1.   0.   1.   0.   0.]
 [ 84. 101.   0.   0.   0.   0.   0.]
 [ 51. 104.   1.   0.   1.   0.   0.]
 [ 69. 102.   0.   0.   0.   0.   0.]
 [ 82. 102.   0.   0.   0.   0.   1.]
 [ 69. 103.   0.   0.   1.   0.   0.]
 [ 44. 104.   1.   0.   0.   1.   0.]
 [ 74. 102.   1.   0.   0.   1.   0.]
 [ 20. 101.   0.   0.   0.   1.   1.]
 [ 12. 104.   0.   0.   0.   0.   0.]
 [ 33. 102.   0.   1.   0.   0.   1.]
 [ 42. 101.   0.   0.   0.   0.   1.]
 [ 65.  99. 

In [29]:
X_train_transformed_df = pd.DataFrame(X_train_transformed)
print(X_train_transformed_df)

       0      1    2    3    4    5    6
0   81.0  101.0  0.0  0.0  0.0  1.0  0.0
1    5.0  100.0  0.0  0.0  1.0  0.0  0.0
2   19.0  100.0  0.0  0.0  1.0  0.0  0.0
3   27.0  100.0  1.0  1.0  0.0  0.0  0.0
4   73.0  103.0  0.0  1.0  0.0  0.0  0.0
..   ...    ...  ...  ...  ...  ...  ...
75  24.0  102.0  0.0  0.0  0.0  0.0  1.0
76  75.0  104.0  0.0  1.0  0.0  0.0  1.0
77  51.0  104.0  1.0  0.0  0.0  0.0  0.0
78  82.0  102.0  0.0  0.0  1.0  0.0  1.0
79  11.0  100.0  0.0  0.0  1.0  0.0  1.0

[80 rows x 7 columns]


 # column transformer

In [32]:
from sklearn.compose import ColumnTransformer
tf  = ColumnTransformer(transformers=[
    ('tf1',SimpleImputer(strategy='mean'),['fever']),
    ('tf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tf3',OneHotEncoder(drop='first',sparse_output=False),['gender','city']),
],remainder='passthrough'
)

In [33]:
X_train_f = tf.fit_transform(X_train)
X_test_f = tf.fit_transform(X_test)